- name: Initial server setup
  hosts: debians
  tasks:
    - name: Only run "update_cache=yes" if the last one is more than 3600 seconds ago
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
    - name: Install "apt-transport-https"
      ansible.builtin.apt:
        pkg: "apt-transport-https"
    - name: Install a list of packages
      ansible.builtin.apt:
        pkg:
          - tree
          - curl
          - wget
          - ufw
          - lsb-release
          - docker.io
          - docker-compose
          - htop
          - git
          - vim
          - sudo
    - name: Allow all access to ssh port
      community.general.ufw:
        rule: allow
        port: '22'
        proto: tcp
    - name: Allow all access to tcp port 80
      community.general.ufw:
        rule: allow
        port: '80'
        proto: tcp
    - name: Allow all access to tcp port 443
      community.general.ufw:
        rule: allow
        port: '443'
        proto: tcp
    - name: Enable UFW
      community.general.ufw:
        state: enabled
- name: Ssh hardening
  hosts: debians
  roles:
    - devsec.hardening.ssh_hardening
  vars:
    ssh_permit_root_login: 'without-password'
